### ISSUE TITLE
how to get the upcoming movies for a given country. 

### ISSUE THREAD

**Issue by virk0009** [LordMike/TMDbLib#146]
Hi
Thanks a lot for this great api. I am struggling to get a list of upcoming movies for india. I tried changed the default language and default country properties, but nothing works.

help will be appreciated. 

regards
Parminder

**Comment by LordMike** [comment]
Hi,

According to the API docs for Upcoming (http://docs.themoviedb.apiary.io/#reference/movies/movieupcoming), you cannot submit Country. So you will get movies for all countries (but their names will be in your chosen language).

I believe this is partly because the data is either non-existent, or a given movie can be "upcoming" in many countries at once. You can ask in the TMDb forums for more details.

What you could do instead, is fetch each upcoming movie and inspect its country property(ies) to filter for Inidia.

Mike.

**Comment by hendrikbl** [comment]
This Feature is now implememted into the API via the region parameter: https://developers.themoviedb.org/3/movies/get-upcoming

Adding this should not be too hard :)

**Comment by LordMike** [comment]
@hendrikbl actually, they explicitly state: "We do not yet support regional queries but this is coming soon." :)

If they do suddenly implement it - poke us again.

**Comment by hendrikbl** [comment]
@LordMike Oh okay, sorry for that. The regions page said "Region supoprt is finally here!" so I thought they implemented it. And the parameter was listed so I did not read the rest of the page.
Thank you anyways :)

**Comment by hendrikbl** [comment]
Sounds funny, but they suddenly implemented it, so heres my poke: 👈 😄

**Comment by orangefrog** [comment]
Hi @LordMike,  I've just started building an application with TMDb integration and your library is making life very easy so thanks!  Is the region support for Showing/Upcoming movies on the road-map or do I need to roll my own methods for the time being?

**Comment by LordMike** [comment]
If possible, you could make a PR for this library?

It should be relatively straightforward to add a new (optional) option to the upcoming API/methods. (remember to extend one or more unit tests :))

**Comment by Naliath** [comment]
fixed in #issue-146 @LordMike can you review and merge?

**Comment by LordMike** [comment]
@orangefrog the code contributed by @Naliath should cover your use case - could you try it out by referencing the TMDbLib project directly?

If all is well, I'll have a new version pushed to Nuget.
