### ISSUE TITLE
The credits only retrieves for latest season

### ISSUE THREAD

**Issue by SounakBanerjee** [LordMike/TMDbLib#158]
Using GetTvShowCredits only returns the credits for the last season. The TheMovieDB API also does the same, but lists individual season credits.
Is there a method by which I can retrieve all credits together for all seasons collectively?

**Comment by LordMike** [comment]
Hi,

I'm not sure what you mean by "lists individual season credits". As I can see it at http://docs.themoviedb.apiary.io/#reference/tv/tvidcredits/get, it only lists crew and cast (as we parse it) ..

Could you elaborate?

**Comment by SounakBanerjee** [comment]
I mean, the credits that are returned, are only the last season credits. Not for earlier seasons.
For example, if a series has two seasons, and there is an actor A in season 1, and another actor B in season 2, I would get only B as the result of the series credits.
So I'm asking, if there is a method which will return both cast of season 1 & 2.
Try 'True Detective' as an example. It does not return 'Woody Harrelson' who starred in season 1. 

I hope I'm able to explain.

Thanks.

"Das beste oder nichts"

**Comment by LordMike** [comment]
Could you link to where it's done pr. season?

I'm missing the part on how to remediate it in this library :)

**Comment by LordMike** [comment]
Now I get it. 

There are multiple methods for TV credits: `/tv/{id}/credits`, `/tv/{id}/season/{season_number}/credits` and `/tv/{id}/season/{season_number}/episode/{episode_number}/credits` (docs in links 1, 2 and 3).

You want a method that does not iterate all seasons, but fetches all credits (separately) in one go. This is not possible right now, but is discussed here: #36.

Unfortunately, due to the design as it is now, it's not possible.

1. http://docs.themoviedb.apiary.io/#reference/tv/tvidcredits
2. http://docs.themoviedb.apiary.io/#reference/tv-seasons/tvidseasonseasonnumbercredits
3. http://docs.themoviedb.apiary.io/#reference/tv-episodes/tvidseasonseasonnumberepisodeepisodenumbercredits
