### ISSUE TITLE
HTML decoding for Plot

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#160]
Hi
it will be great if you can add HTML decoding for plot. This is the only field that can have encoded characters:
https://www.themoviedb.org/talk/564ae26bc3a3686031002638

It's no problem to decode it in my code, but i think it will be great to receive all API results in decoded format (like Title is by default).

**Comment by LordMike** [comment]
From what I see, it's the field `overview`, right?
I wonder how we could do that without depending on something crazy like `System.Web`.

**Comment by LordMike** [comment]
I can otherwise see the point in ensuring that *all* fields are "raw"... And not all except a few here and there.

**Comment by LordMike** [comment]
Asked travis if he'll fix it in his end..

**Comment by DanCooper** [comment]
Yes, I meant Overview.
Thanks for asking Travis.

**Comment by mike-csis** [comment]
@Naliath, reg. what happens if Travis decides to do something. In the talk above, Travis writes:

"Hey Mike,

If there is ever a v4, yes, this would change and be how it gets returned but at this point there's too many clients expecting the data back in the current format. I don't like to make to data changes if I don't have to. It's been this way since 2012 (when v3 launched) so I will leave it be for now."

So .. We should be safe.

**Comment by LordMike** [comment]
@Naliath, reg. what happens if Travis decides to do something. In the talk above, Travis writes:

"Hey Mike,

If there is ever a v4, yes, this would change and be how it gets returned but at this point there's too many clients expecting the data back in the current format. I don't like to make to data changes if I don't have to. It's been this way since 2012 (when v3 launched) so I will leave it be for now."

So .. We should be safe.

**Comment by Naliath** [comment]
Should be fine, worst case is that we would decode already decoded data and might replace characters that should not be replaced. This will only present an issue in very few cases so nothing to worry about.

Date: Thu, 26 Nov 2015 01:23:24 -0800

**Comment by LordMike** [comment]
Agreed. The moment v4 comes out, if ever, we'll push for unencoded data.

-----Original Message-----
