### ISSUE TITLE
MonoAndroid framework compatibility

### ISSUE THREAD

**Issue by johnruth** [LordMike/TMDbLib#190]
I'm working on a Xamarin native Android app and I got the following error when trying to add the NuGet package.

"Could not install package 'TMDbLib 0.9.0.3-alpha'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework."

I'm not too familiar with this topic so hopefully this isn't a duplicate issue.

**Comment by LordMike** [comment]
Apparently my response to the email didn't reach here.
Heres what I wrote:

We only target .net 4. So any other framework will need a specific build for it.
 
You can fetch the source code instead, and then change the target to monoandroid. Then reference your version of the library rather than the nuget.
