### ISSUE TITLE
How to use DiscoverMoviesAsync method

### ISSUE THREAD

**Issue by gabiionut** [LordMike/TMDbLib#233]
I want to get images of movies ordered by popularity but I don't know what to do with the data returned by this call `client.DiscoverMoviesAsync().OrderBy(DiscoverMovieSortBy.Popularity);`. It seems that the data type returned is `DiscoverMovie` so I can't use `GetImageUrl` method. Can you show me how to use `DiscoverMoviesAsync` method ?

**Comment by LordMike** [comment]
The Discover method is different from the rest, because adding all its options in one long method definition would be extremely hard to use. 

Once you've constructed your DiscoverMovie object by setting all the filtering options you need, you perform the actual search by running `<DiscoverMovie object>.Query()`. 

:)
