### ISSUE TITLE
Use Async/Await for GetConfig method

### ISSUE THREAD

**Issue by bbougot** [LordMike/TMDbLib#236]
https://github.com/LordMike/TMDbLib/blob/2e90311a528182adb13fc1a6aa1683893aa47a50/TMDbLib/Client/TMDbClient.cs#L168

**Comment by LordMike** [comment]
... there was a reason why this wasn't `async`... I fail to recall right now though.

**Comment by Naliath** [comment]
I figure it might cause issues since you need to config to do anything else. This can be mitigated though by just directly awaiting it. So I guess we can change it and see if something explodes?

Thing is that in essence this is a sync method no mather how you turn it. It also does not return a result itself. So perhaps this just needs to be redesigned?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LordMike** [comment]
Perhaps turn it into a `GetConfigIfNeeded` that is awaitable, which will check if a cached one is present. Any method needing will just call this with await, and await the result..

This is internal. Then externally, we'll present a `GetConfig` that does just that.

As a bonus, we could then _copy_ the result of a `GetConfig` call into our cache.
