### ISSUE TITLE
In KnownForBase class, Title is missing

### ISSUE THREAD

**Issue by Bitgamey** [LordMike/TMDbLib#271]
Since Title is missing, I am unable to retrieve the title when sending an actor's name and needing to access what they are 'known_for'.
     
public abstract class KnownForBase
    {
        protected KnownForBase();
        public string BackdropPath { get; set; }
        public List<int> GenreIds { get; set; }
        public int Id { get; set; }
        public MediaType MediaType { get; set; }
        public string OriginalLanguage { get; set; }
        public string Overview { get; set; }
        public double Popularity { get; set; }
        public string PosterPath { get; set; }
        public double VoteAverage { get; set; }
        public int VoteCount { get; set; }

**Comment by LordMike** [comment]
Please submit a PR. :)

**Comment by FrederikBolding** [comment]
This isn't true, not every `KnownFor` object should have a title. TV shows have `name` instead of `title`, while movies have titles. It's present on the `KnownForMovie` object, which the library is casting to 😄 . 

Is there a specific instance in which you're not receving the casted object? I just tested with `GetPersonListAsync`, which worked correctly.

**Comment by FrederikBolding** [comment]
If this was simply a misunderstanding this can be closed.
