### ISSUE TITLE
How do i use DiscoverMovies by Genres? 

### ISSUE THREAD

**Issue by DenisAndrei** [LordMike/TMDbLib#334]
client.DiscoverMoviesAsync().IncludeWithAllOfGenre().Query(1).Result;
Please, what do i need to to write in parentheses to get the movie genre i want?

**Comment by LordMike** [comment]
As you can see here: https://github.com/LordMike/TMDbLib/blob/25cb88c2649a11305f74b5af5d43d13618ae8161/TMDbLib/Objects/Discover/DiscoverMovie.cs#L129-L145

You need to provide genres. So either get some Genres from the API, or provide a list of Genre Id's. (I can see the parameter is named `castIds`, so that parts wrong).
